# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy object storage

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        if [ -f .ovh/requirements.txt ]; then pip3 install -r .ovh/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Deploy Object Storage
      run: |
        cd .ovh
        OVH_ENDPOINT=ovh-eu OVH_APPLICATION_KEY=${{ secrets.OVH_APPLICATION_KEY }} OVH_APPLICATION_SECRET=${{ secrets.OVH_APPLICATION_SECRET }} OVH_CONSUMER_KEY=${{ secrets.OVH_CONSUMER_KEY }} python3 create_environment.py object-storage-1

